name: environment
channels: 
  - conda-forge
dependencies: 
  - python=3.11.7
  - scanpy>=1.11.5
  - anndata>=0.12.10
  - numpy>=2.4.3
  - pandas>=2.3.3
  - matplotlib>=3.10.8
  - tqdm>=4.66.1
  - plotly>=5.19.0
  - ipykernel
  - pytest>=7.4.0
  - sphinx>=7.2.6
  - sphinx-rtd-theme
  - nbsphinx
  - notebook
  - r-irkernel
  - bash_kernel
  - docutils
  - pygments
  - babel
  - importlib_metadata
  - jupyter_core>=5.1.3
